// <auto-generated />
using System;
using BookLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414062432_CreateLibrary")]
    partial class CreateLibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BookLibrary.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Лев Толстой",
                            DateAdded = new DateTime(2026, 4, 14, 9, 24, 31, 774, DateTimeKind.Local).AddTicks(187),
                            Genre = "Роман-эпопея",
                            ISBN = "9785170909373",
                            Title = "Война и мир",
                            Year = 1869
                        },
                        new
                        {
                            Id = 2,
                            Author = "Фёдор Достоевский",
                            DateAdded = new DateTime(2026, 4, 14, 9, 24, 31, 774, DateTimeKind.Local).AddTicks(189),
                            Genre = "Роман",
                            ISBN = "9785171180804",
                            Title = "Преступление и наказание",
                            Year = 1866
                        },
                        new
                        {
                            Id = 3,
                            Author = "Михаил Булгаков",
                            DateAdded = new DateTime(2026, 4, 14, 9, 24, 31, 774, DateTimeKind.Local).AddTicks(192),
                            Genre = "Мистический роман",
                            ISBN = "9785170922877",
                            Title = "Мастер и Маргарита",
                            Year = 1967
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
